// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NobetArasi.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NobetArasi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NobetArasi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Etkenler, tanı ipuçları ve temel klinik bilgiler.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Mikrobiyoloji",
                            Slug = "mikrobiyoloji"
                        },
                        new
                        {
                            Id = 2,
                            Description = "İlaç grupları, yan etkiler ve mekanizmalar.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Farmakoloji",
                            Slug = "farmakoloji"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hastalık mekanizmaları ve ayırıcı noktalar.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Patoloji",
                            Slug = "patoloji"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Klinik yaklaşım ve sık karşılaşılan tablolar.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Dahiliye",
                            Slug = "dahiliye"
                        });
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TusNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Lober pnömoni ve paslı balgam klasik olarak S. pneumoniae ile ilişkilidir.",
                            IsActive = true,
                            OptionA = "Streptococcus pneumoniae",
                            OptionB = "Mycoplasma pneumoniae",
                            OptionC = "Klebsiella pneumoniae",
                            OptionD = "Staphylococcus aureus",
                            QuestionText = "Paslı balgam ile seyreden lober pnömonide en olası etken hangisidir?",
                            TusNote = "Lober pnömoni + paslı balgam → S. pneumoniae."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CorrectOption = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Bakteriyel menenjitte BOS'ta nötrofil ve protein artar, glukoz düşer.",
                            IsActive = true,
                            OptionA = "Lenfosit artışı, glukoz normal",
                            OptionB = "Nötrofil artışı, glukoz düşük",
                            OptionC = "Protein düşük, glukoz yüksek",
                            OptionD = "Eritrosit artışı, protein normal",
                            QuestionText = "Bakteriyel menenjitte BOS bulguları için en uygun ifade hangisidir?",
                            TusNote = "Bakteriyel menenjit → nötrofil ↑, protein ↑, glukoz ↓."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CorrectOption = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Beta-laktamlar bakteri hücre duvarı sentezini inhibe eder.",
                            IsActive = true,
                            OptionA = "Protein sentezini inhibe etmek",
                            OptionB = "Hücre duvarı sentezini inhibe etmek",
                            OptionC = "DNA girazı aktive etmek",
                            OptionD = "Folat sentezini artırmak",
                            QuestionText = "Beta-laktam antibiyotiklerin temel etki mekanizması nedir?",
                            TusNote = "Beta-laktam → hücre duvarı sentezi inhibisyonu."
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "ACE inhibitörleri bradikinin artışıyla kuru öksürük yapabilir.",
                            IsActive = true,
                            OptionA = "Kuru öksürük",
                            OptionB = "Hipoglisemi",
                            OptionC = "İşitme kaybı",
                            OptionD = "Diş eti hipertrofisi",
                            QuestionText = "ACE inhibitörlerinin sık görülen yan etkilerinden biri hangisidir?",
                            TusNote = "ACE inhibitörü → kuru öksürük, hiperkalemi, anjiyoödem."
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Apoptoz kontrollü/programlı hücre ölümüdür.",
                            IsActive = true,
                            OptionA = "Kontrollü hücre ölümü",
                            OptionB = "Her zaman inflamasyonla gider",
                            OptionC = "Sadece bakterilerde olur",
                            OptionD = "Nekroz ile tamamen aynıdır",
                            QuestionText = "Apoptoz için en uygun ifade hangisidir?",
                            TusNote = "Apoptoz → kontrollü hücre ölümü."
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Akut inflamasyonda nötrofiller baskındır.",
                            IsActive = true,
                            OptionA = "Nötrofil",
                            OptionB = "Fibroblast",
                            OptionC = "Plazma hücresi",
                            OptionD = "Adiposit",
                            QuestionText = "Akut inflamasyonda baskın hücre genellikle hangisidir?",
                            TusNote = "Akut inflamasyon → nötrofil."
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Primer hipotiroidide genellikle TSH yüksekliği beklenir.",
                            IsActive = true,
                            OptionA = "TSH yüksekliği",
                            OptionB = "TSH düşüklüğü",
                            OptionC = "Troponin yüksekliği",
                            OptionD = "Amilaz düşüklüğü",
                            QuestionText = "Hipotiroidide beklenen laboratuvar bulgusu hangisidir?",
                            TusNote = "Primer hipotiroidi → TSH ↑."
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CorrectOption = "A",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            Explanation = "Demir eksikliği anemisi tipik olarak mikrositik hipokrom anemi yapar.",
                            IsActive = true,
                            OptionA = "Mikrositik anemi",
                            OptionB = "Makrositik anemi",
                            OptionC = "Lökositoz olmadan tanı konulamaz",
                            OptionD = "Trombosit sıfırlanır",
                            QuestionText = "Demir eksikliği anemisinde beklenen bulgulardan biri hangisidir?",
                            TusNote = "Demir eksikliği → mikrositik hipokrom anemi."
                        });
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedXp")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("quiz_attempts", (string)null);
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.QuizAttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuizAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.ToTable("quiz_attempt_answers", (string)null);
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuizCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWrongCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_progresses", (string)null);
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.Question", b =>
                {
                    b.HasOne("NobetArasi.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("NobetArasi.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NobetArasi.Domain.Entities.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.QuizAttemptAnswer", b =>
                {
                    b.HasOne("NobetArasi.Domain.Entities.Question", "Question")
                        .WithMany("QuizAttemptAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NobetArasi.Domain.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("NobetArasi.Domain.Entities.User", "User")
                        .WithOne("Progress")
                        .HasForeignKey("NobetArasi.Domain.Entities.UserProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.Question", b =>
                {
                    b.Navigation("QuizAttemptAnswers");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("NobetArasi.Domain.Entities.User", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
